import { toast } from "sonner";
import { cases, alerts, type Case, type Alert } from "@/lib/mock-data";

const BACKEND_URL = "http://localhost:8000";

const STORAGE_CASES_KEY = "vikshaka_cases_db";
const STORAGE_ALERTS_KEY = "vikshaka_alerts_db";

export interface BackendStatus {
  connected: boolean;
  version?: string;
  dataset: "realtime_backend" | "synthetic_browser";
}

class APIClientService {
  private isConnected: boolean = false;

  constructor() {
    this.initLocalStorage();
  }

  private initLocalStorage() {
    if (typeof window === "undefined") return;
    if (!localStorage.getItem(STORAGE_CASES_KEY)) {
      localStorage.setItem(STORAGE_CASES_KEY, JSON.stringify(cases));
    }
    if (!localStorage.getItem(STORAGE_ALERTS_KEY)) {
      localStorage.setItem(STORAGE_ALERTS_KEY, JSON.stringify(alerts));
    }
  }

  async checkHealth(): Promise<BackendStatus> {
    try {
      const res = await fetch(`${BACKEND_URL}/health`, { signal: AbortSignal.timeout(1500) });
      if (res.ok) {
        this.isConnected = true;
        const data = await res.json();
        return { connected: true, version: data.version, dataset: "realtime_backend" };
      }
    } catch (e) {
      this.isConnected = false;
    }
    return { connected: false, dataset: "synthetic_browser" };
  }

  async getCases(): Promise<Case[]> {
    try {
      const res = await fetch(`${BACKEND_URL}/api/v1/records/cases`, { signal: AbortSignal.timeout(1500) });
      if (res.ok) {
        const data = await res.json();
        return data;
      }
    } catch (e) {
      // Fallback to synthetic browser DB
    }
    
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem(STORAGE_CASES_KEY);
      if (stored) return JSON.parse(stored);
    }
    return cases;
  }

  async generateSyntheticCaseRecord(): Promise<Case> {
    try {
      const res = await fetch(`${BACKEND_URL}/api/v1/records/cases/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: AbortSignal.timeout(2000),
      });
      if (res.ok) {
        const body = await res.json();
        toast.success(`FastAPI Backend generated synthetic case: ${body.generated_case.id}`);
        return body.generated_case;
      }
    } catch (e) {
      // Fallback synthetic generator
    }

    // Local synthetic generator
    const crimeTypes = ["Cyber Fraud", "Armed Robbery", "Narcotics", "Identity Theft", "Homicide", "White Collar"];
    const districts = ["Bengaluru South", "Central Delhi", "Bandra Mumbai", "Salt Lake Sector V", "T. Nagar Chennai"];
    const randCrime = crimeTypes[Math.floor(Math.random() * crimeTypes.length)];
    const randDist = districts[Math.floor(Math.random() * districts.length)];
    const id = `VK-SYN-${Math.floor(1000 + Math.random() * 9000)}`;

    const newCase: Case = {
      id,
      fir: `FIR/2026/${Math.floor(100 + Math.random() * 900)}`,
      title: `Synthetic Intelligence — ${randCrime} in ${randDist}`,
      ipc: "IPC 392, 420",
      crimeType: randCrime,
      district: randDist,
      state: "Multi-State",
      status: "investigating",
      priority: Math.random() > 0.5 ? "critical" : "high",
      suspect: `Suspect ID-${Math.floor(100 + Math.random() * 900)}`,
      officer: "AI Telemetry Core",
      reportedAt: new Date().toISOString().replace("T", " ").substring(0, 16),
      updatedAt: new Date().toISOString().replace("T", " ").substring(0, 16),
      summary: "Synthetic record auto-generated by VIKSHAKA AI Telemetry Engine.",
    };

    if (typeof window !== "undefined") {
      const existing = await this.getCases();
      const updated = [newCase, ...existing];
      localStorage.setItem(STORAGE_CASES_KEY, JSON.stringify(updated));
    }

    toast.success(`Synthetic Case Record Generated: ${newCase.id}`);
    return newCase;
  }

  async getAlerts(): Promise<Alert[]> {
    try {
      const res = await fetch(`${BACKEND_URL}/api/v1/records/alerts`, { signal: AbortSignal.timeout(1500) });
      if (res.ok) {
        return await res.json();
      }
    } catch (e) {
      // Fallback
    }

    if (typeof window !== "undefined") {
      const stored = localStorage.getItem(STORAGE_ALERTS_KEY);
      if (stored) return JSON.parse(stored);
    }
    return alerts;
  }

  async triggerLiveDispatchAlert(title: string, severity: "critical" | "high" | "medium" = "high"): Promise<Alert> {
    const alert: Alert = {
      id: `A-${Math.floor(9000 + Math.random() * 999)}`,
      time: new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: false }),
      severity,
      category: "Real-time Telemetry",
      title,
      location: "Bengaluru South",
      officer: "AI Dispatch Engine",
    };

    try {
      await fetch(`${BACKEND_URL}/api/v1/records/alerts/trigger?title=${encodeURIComponent(title)}&severity=${severity}`, {
        method: "POST",
        signal: AbortSignal.timeout(1500),
      });
    } catch (e) {
      // Fallback
    }

    if (typeof window !== "undefined") {
      const existing = await this.getAlerts();
      localStorage.setItem(STORAGE_ALERTS_KEY, JSON.stringify([alert, ...existing]));
    }

    toast.error(`LIVE DISPATCH ALERT: ${title}`);
    return alert;
  }
}

export const apiClient = new APIClientService();
