from __future__ import annotations
import random
from datetime import datetime, timedelta
from typing import List, Optional
from fastapi import APIRouter, Query
from pydantic import BaseModel

router = APIRouter(prefix="/api/v1/records", tags=["records"])

# Synthetic state generator
CRIME_TYPES = ["Armed Robbery", "Cyber Fraud", "Theft", "Narcotics", "Homicide", "Auto Theft", "White Collar", "Smuggling"]
DISTRICTS = ["Bengaluru South", "New Delhi", "Bandra, Mumbai", "Bidhannagar, Kolkata", "T. Nagar, Chennai", "Bapunagar, Ahmedabad"]
STATES = ["Karnataka", "Delhi", "Maharashtra", "West Bengal", "Tamil Nadu", "Gujarat"]

class CaseRecord(BaseModel):
    id: str
    fir: str
    title: str
    ipc: str
    crimeType: str
    district: str
    state: str
    status: str
    priority: str
    suspect: str
    officer: str
    reportedAt: str
    updatedAt: str
    summary: str

class AlertRecord(BaseModel):
    id: str
    time: str
    severity: str
    category: str
    title: str
    location: str
    officer: str

# In-memory synthetic database
SYNTHETIC_CASES: List[dict] = [
    {
        "id": "VK-BLR-2024-0421",
        "fir": "FIR/2024/00421",
        "title": "Armed robbery at Jayanagar jewellery store",
        "ipc": "IPC 392, 397",
        "crimeType": "Armed Robbery",
        "district": "Bengaluru South",
        "state": "Karnataka",
        "status": "investigating",
        "priority": "critical",
        "suspect": "Ravi 'Bull' Naidu + 2 associates",
        "officer": "Insp. Anjali Rao",
        "reportedAt": "2026-07-18 02:14",
        "updatedAt": "2026-07-22 19:40",
        "summary": "Three masked assailants breached rear service door at 02:04 IST. Estimated ₹1.4 Cr taken."
    },
    {
        "id": "VK-DEL-2024-0910",
        "fir": "FIR/2024/00910",
        "title": "Cyber fraud ring — pan-India OTP scam",
        "ipc": "IPC 420, IT Act 66C",
        "crimeType": "Cyber Fraud",
        "district": "New Delhi",
        "state": "Delhi",
        "status": "investigating",
        "priority": "high",
        "suspect": "Sundar Halwai (kingpin), 6 mules identified",
        "officer": "ACP Kabir Verma",
        "reportedAt": "2026-07-11 09:22",
        "updatedAt": "2026-07-22 14:11",
        "summary": "Ring operating from Jamtara cluster with ₹3.2 Cr losses across 8 states."
    }
]

SYNTHETIC_ALERTS: List[dict] = [
    {
        "id": "A-9001",
        "time": "22:14",
        "severity": "critical",
        "category": "Armed Incident",
        "title": "Panic alarm — Jayanagar jewellery cluster",
        "location": "Bengaluru South",
        "officer": "Insp. Anjali Rao"
    },
    {
        "id": "A-9000",
        "time": "22:08",
        "severity": "critical",
        "category": "Weapon Detection",
        "title": "AI flagged pistol on CAM-118",
        "location": "Karol Bagh, Delhi",
        "officer": "ACP Kabir Verma"
    }
]

@router.get("/cases")
def get_all_cases(priority: Optional[str] = None):
    if priority:
        return [c for c in SYNTHETIC_CASES if c["priority"] == priority]
    return SYNTHETIC_CASES

@router.post("/cases/generate")
def generate_synthetic_case():
    new_id = f"VK-SYN-{random.randint(1000, 9999)}"
    crime = random.choice(CRIME_TYPES)
    idx = random.randint(0, len(DISTRICTS) - 1)
    
    new_case = {
        "id": new_id,
        "fir": f"FIR/2026/{random.randint(100, 999)}",
        "title": f"Synthetic Incident — {crime} in {DISTRICTS[idx]}",
        "ipc": "IPC 392, 420",
        "crimeType": crime,
        "district": DISTRICTS[idx],
        "state": STATES[idx],
        "status": "investigating",
        "priority": random.choice(["critical", "high", "medium"]),
        "suspect": f"Suspect ID-{random.randint(100, 999)}",
        "officer": "AI Automated IO",
        "reportedAt": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "updatedAt": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "summary": f"Automated synthetic record generated by VIKSHAKA AI Telemetry Core."
    }
    
    SYNTHETIC_CASES.insert(0, new_case)
    return {"status": "success", "generated_case": new_case, "total_records": len(SYNTHETIC_CASES)}

@router.get("/alerts")
def get_live_alerts():
    return SYNTHETIC_ALERTS

@router.post("/alerts/trigger")
def trigger_synthetic_alert(title: str, severity: str = "high", location: str = "Bengaluru"):
    alert = {
        "id": f"A-{random.randint(9000, 9999)}",
        "time": datetime.now().strftime("%H:%M"),
        "severity": severity,
        "category": "Real-time Telemetry",
        "title": title,
        "location": location,
        "officer": "AI Autonomous Telemetry"
    }
    SYNTHETIC_ALERTS.insert(0, alert)
    return {"status": "triggered", "alert": alert}
