/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PatrolRouteImport } from './routes/patrol'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as HotspotsRouteImport } from './routes/hotspots'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrolRoute = PatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const HotspotsRoute = HotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/dashboard': typeof DashboardRoute
  '/hotspots': typeof HotspotsRoute
  '/networks': typeof NetworksRoute
  '/patrol': typeof PatrolRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/dashboard': typeof DashboardRoute
  '/hotspots': typeof HotspotsRoute
  '/networks': typeof NetworksRoute
  '/patrol': typeof PatrolRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/dashboard': typeof DashboardRoute
  '/hotspots': typeof HotspotsRoute
  '/networks': typeof NetworksRoute
  '/patrol': typeof PatrolRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/cases'
    | '/cctv'
    | '/dashboard'
    | '/hotspots'
    | '/networks'
    | '/patrol'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/cases'
    | '/cctv'
    | '/dashboard'
    | '/hotspots'
    | '/networks'
    | '/patrol'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analysis'
    | '/auth'
    | '/cases'
    | '/cctv'
    | '/dashboard'
    | '/hotspots'
    | '/networks'
    | '/patrol'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRoute
  CctvRoute: typeof CctvRoute
  DashboardRoute: typeof DashboardRoute
  HotspotsRoute: typeof HotspotsRoute
  NetworksRoute: typeof NetworksRoute
  PatrolRoute: typeof PatrolRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrol': {
      id: '/patrol'
      path: '/patrol'
      fullPath: '/patrol'
      preLoaderRoute: typeof PatrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotspots': {
      id: '/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof HotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRoute,
  CctvRoute: CctvRoute,
  DashboardRoute: DashboardRoute,
  HotspotsRoute: HotspotsRoute,
  NetworksRoute: NetworksRoute,
  PatrolRoute: PatrolRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
